### ISSUE TITLE
Offensive content warnings

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/pastebin-grab#2]
`Pastebin’s SMART filters have detected potentially offensive or questionable content ahead.` warnings aren't bypassed. Cf. IRC on  2020-10-11.

**Comment by Arkiver2** [comment]
added support with https://github.com/ArchiveTeam/pastebin-grab/commit/1e88c5ff254599aa42ea122513cd710f6d27edc4
